
services:
  postgres:
    image: postgres:16
    container_name: pg-subscriptions
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subscriptions"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: dev
      HTTP_PORT: "8080"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/subscriptions?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  pgdata: {}